update
upgrade

tap homebrew/dupes
tap josegonzalez/homebrew-php
tap phinze/cask
tap caskroom/versions

update

install bash grep ack
install wget --enable-iri
install imagemagick
install mysql node ruby git nginx
install vim --override-system-vi
install bash-completion
install valgrind
install brew-cask

install php55 --with-fpm --with-gmp --without-pear
install php55-xdebug php55-vld php55-intl php55-imagick php55-apcu

cask install google-chrome firefox opera evernote appcleaner vlc steam transmission teamviewer skype
cask install sequel-pro phpstorm github sublime-text3 vagrant mou

# Remove outdated versions from the cellar
cleanup
